apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-connection-configmap
  namespace: app
  labels:
    app: pdss-back
data:
  db-connection-string: jdbc:sqlserver://pdss-db.database.windows.net:1433;database=${{secrets.AZURE_MYSQL_DB}};user=${{secrets.AZURE_MYSQL_ADMIN_USER}}@pdss-db;password=${{secrets.AZURE_MYSQL_ADMIN_PWD}};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
